name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{ cron: "0 3 * * *" }]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: { branches: ["main"] }

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: achievements
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: arzkar
          base: ""
          plugin_achievements: yes
          plugin_achievements_threshold: B # Display achievements with rank B or higher
          plugin_achievements_secrets: yes # Display unlocked secrets achievements
          plugin_achievements_display: detailed # Use detailed display
          plugin_achievements_limit: 0 # Display all unlocked achievements (no limit)

      - name: header
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/header.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: arzkar
          template: classic
          base: header
          config_timezone: ${{ secrets.USER_TIMEZONE }}

      - name: acti_comm
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/acti_comm.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: arzkar
          template: classic
          base: activity, community
          config_timezone: ${{ secrets.USER_TIMEZONE }}

      - name: iso_calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/iso_calender.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: arzkar
          template: classic
          base: ""
          config_timezone: ${{ secrets.USER_TIMEZONE }}
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

      - name: langs_used
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/langs_used.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: arzkar
          template: classic
          base: ""
          config_timezone: ${{ secrets.USER_TIMEZONE }}
          plugin_followup: yes
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_ignored: |
            html, css, tex, less, dockerfile, makefile, qmake, lex, 
            cmake, shell, gnuplot, Jupyter Notebook, Batchfile, Procfile, 
            Inno Setup, Elixir, Vim Script
          plugin_languages_details: bytes-size, percentage

      - name: notable_contributions
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/notable_contributions.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: arzkar
          template: classic
          base: ""
          config_timezone: ${{ secrets.USER_TIMEZONE }}
          plugin_notable: yes
          plugin_notable_from: all
          plugin_notable_indepth: yes
          plugin_notable_repositories: yes
