name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{ cron: "0 3 * * *" }]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: { branches: ["main"] }

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: arzkar/metrics@latest
        with:
          filename: .metrics/achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: arzkar
          base: achievements
          plugin_achievements: yes
          plugin_achievements_threshold: B # Display achievements with rank B or higher
          plugin_achievements_secrets: yes # Display unlocked secrets achievements
          plugin_achievements_display: detailed # Use compact display
          plugin_achievements_limit: 0 # Display all unlocked achievements (no limit)

      - name: header
        uses: arzkar/metrics@latest
        with:
          filename: .metrics/header.svg
          # You'll need to setup a personal token in your secrets.
          token: ${{ secrets.METRICS_TOKEN }}
          # GITHUB_TOKEN is a special auto-generated token used for commits
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          # Options
          user: arzkar
          template: classic
          base: header
          config_timezone: ${{ secrets.USER_TIMEZONE }}

      - name: acti_comm
        uses: arzkar/metrics@latest
        with:
          filename: .metrics/acti_comm.svg
          # You'll need to setup a personal token in your secrets.
          token: ${{ secrets.METRICS_TOKEN }}
          # GITHUB_TOKEN is a special auto-generated token used for commits
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          # Options
          user: arzkar
          template: classic
          base: activity, community
          config_timezone: ${{ secrets.USER_TIMEZONE }}

      - name: iso_calendar
        uses: arzkar/metrics@latest
        with:
          filename: .metrics/iso_calender.svg
          # You'll need to setup a personal token in your secrets.
          token: ${{ secrets.METRICS_TOKEN }}
          # GITHUB_TOKEN is a special auto-generated token used for commits
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          # Options
          user: arzkar
          template: classic
          base: ""
          config_timezone: ${{ secrets.USER_TIMEZONE }}
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

      - name: langs_used
        uses: arzkar/metrics@latest
        with:
          filename: .metrics/langs_used.svg
          # You'll need to setup a personal token in your secrets.
          token: ${{ secrets.METRICS_TOKEN }}
          # GITHUB_TOKEN is a special auto-generated token used for commits
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          # Options
          user: arzkar
          template: classic
          base: ""
          config_timezone: ${{ secrets.USER_TIMEZONE }}
          plugin_followup: yes
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_ignored: |
          html, css, tex, less, dockerfile, makefile, qmake, lex, 
          cmake, shell, gnuplot, Jupyter Notebook, Batchfile, Procfile, 
          Inno Setup, Elixir, Vim Script
          plugin_languages_details: bytes-size, percentage

      - name: repositories
        uses: arzkar/metrics@latest
        with:
          filename: .metrics/repositories.svg
          # You'll need to setup a personal token in your secrets.
          token: ${{ secrets.METRICS_TOKEN }}
          # GITHUB_TOKEN is a special auto-generated token used for commits
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          # Options
          user: arzkar
          template: classic
          base: repositories
          config_timezone: ${{ secrets.USER_TIMEZONE }}

      - name: Notable Contributions
        uses: lowlighter/metrics@latest
        with:
          filename: .metrics/notable_contributions.svg
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_notable: yes
          plugin_notable_indepth: yes
          plugin_notable_repositories: yes

          # Options
          user: arzkar
          template: classic
          base: ""
          config_timezone: ${{ secrets.USER_TIMEZONE }}
